authors:
  david:
    name: D.Hasselhoff
    description: Retter der 80er
    avatar: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Hoff_3.jpg/800px-Hoff_3.jpg
  helge:
    name: H.Schneider
    description: Amtierender Bundspräsident
    avatar: https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Maischberger_-_2023-02-08-6654.jpg/1280px-Maischberger_-_2023-02-08-6654.jpg